"""init

Revision ID: e4b369cef3c2
Revises: 
Create Date: 2018-06-10 09:23:22.145816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b369cef3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('devicetype', sa.String(length=15), nullable=True),
    sa.Column('loc', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_ip'), 'device', ['ip'], unique=True)
    op.create_table('peer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_active', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('bytes_tr', sa.String(length=60), nullable=True),
    sa.Column('connection', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_ip'), 'peer', ['ip'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peer_ip'), table_name='peer')
    op.drop_table('peer')
    op.drop_index(op.f('ix_device_ip'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
